spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  aws:
    region: ${APP_AWS_REGION}
  sqs:
    queueUrl: ${APP_SQS_QUEUE_URL}
